window.onload = function(){

let saved = localStorage.getItem("tarvex_prompt")

if(saved){
document.getElementById("prompt").value = saved
}

};

const TARVEX_EMAIL = "tarvexnetworks@gmail.com";

let siteData = {}

function generate(){

let text = document.getElementById("prompt").value

if(text==""){
alert("Describe website first")
return
}

/* BRAND */

let words = text.split(" ")
let brand = words[0] + "ly"
brand = brand.charAt(0).toUpperCase() + brand.slice(1)

let tagline = "Build smarter with " + brand

/* NAV */

let nav = `
<div style="background:#0b2a5b;color:white;padding:20px">
<h2>${brand}</h2>
<small>${tagline}</small>
<br><br>

<a href="#" onclick="loadPage('index')" style="color:white;margin-right:15px">Home</a>
<a href="#" onclick="loadPage('about')" style="color:white;margin-right:15px">About</a>
<a href="#" onclick="loadPage('services')" style="color:white;margin-right:15px">Services</a>
<a href="#" onclick="loadPage('contact')" style="color:white">Contact</a>

</div>
`

/* HERO */

let hero = `
<div style="padding:60px;text-align:center">
<h1>${brand}</h1>
<p>${text}</p>

<button style="
padding:14px 22px;
background:#0b2a5b;
color:white;
border:none;
border-radius:6px;
margin-top:10px">
Start Building
</button>
</div>
`

/* FEATURES */

let features = `
<div style="padding:40px">

<h2>Features</h2>

<div style="display:flex;gap:20px;flex-wrap:wrap">

<div style="background:#f4f4f4;padding:20px;flex:1">
AI Website Builder
</div>

<div style="background:#f4f4f4;padding:20px;flex:1">
Instant Deployment
</div>

<div style="background:#f4f4f4;padding:20px;flex:1">
Modern Design
</div>

</div>

</div>
`

/* PRICING */

let pricing = `
<div style="padding:40px">

<h2>Pricing</h2>

<div style="display:flex;gap:20px;flex-wrap:wrap">

<div style="border:1px solid #ddd;padding:20px;flex:1">
<h3>Starter</h3>
<p>$5</p>
</div>

<div style="border:1px solid #ddd;padding:20px;flex:1">
<h3>Pro</h3>
<p>$15</p>
</div>

<div style="border:1px solid #ddd;padding:20px;flex:1">
<h3>Business</h3>
<p>$30</p>
</div>

</div>

</div>
`

/* TESTIMONIALS */

let testimonials = `
<div style="padding:40px">

<h2>Testimonials</h2>

<p>"Amazing AI builder" — User</p>
<p>"Built my website in seconds" — Client</p>

</div>
`

/* FOOTER */

let footer = `
<div style="background:#0b2a5b;color:white;padding:20px;text-align:center">
${brand} powered by Tarvex  
<br>
${TARVEX_EMAIL}
</div>
`

/* HOME */

siteData.index = `
${nav}
${hero}
${features}
${pricing}
${testimonials}
${footer}
`

/* ABOUT */

siteData.about = `
${nav}

<div style="padding:40px">
<h1>About ${brand}</h1>
<p>This website was generated by Tarvex AI</p>
</div>

${footer}
`

/* SERVICES */

siteData.services = `
${nav}

<div style="padding:40px">
<h1>Services</h1>

<ul>
<li>AI Website Builder</li>
<li>Hosting</li>
<li>Domains</li>
<li>Deployment</li>
</ul>

</div>

${footer}
`

/* CONTACT */

siteData.contact = `
${nav}

<div style="padding:40px">
<h1>Contact</h1>
<p>Email: ${TARVEX_EMAIL}</p>
</div>

${footer}
`

document.getElementById("result").style.display="block"

document.getElementById("result").innerHTML = `
<h3>Website Preview</h3>

<div id="preview" style="background:white;color:black">
${siteData.index}
</div>

<button onclick="deploy()">Deploy Website</button>
`

}

function loadPage(page){
document.getElementById("preview").innerHTML = siteData[page]
}

function deploy(){
localStorage.setItem("tarvex_site", JSON.stringify(siteData))
window.location.href="deploy.html"
  }
