let siteData = {}

function generate(){

let text = document.getElementById("prompt").value

if(text==""){
alert("Describe your app idea")
return
}

/* BRAND */

let brand = text.split(" ")[0]
brand = brand.charAt(0).toUpperCase() + brand.slice(1)

/* NAV */

let nav = `
<div style="background:#02110d;color:white;padding:20px">
<h2>${brand}</h2>

<a href="#" onclick="loadPage('home')" style="color:white;margin-right:15px">Home</a>
<a href="#" onclick="loadPage('about')" style="color:white;margin-right:15px">About</a>
<a href="#" onclick="loadPage('services')" style="color:white;margin-right:15px">Services</a>
<a href="#" onclick="loadPage('contact')" style="color:white">Contact</a>

</div>
`

/* HERO */

let hero = `
<div style="padding:60px;text-align:center">
<h1>${brand}</h1>
<p>${text}</p>

<button style="
padding:14px 22px;
background:#00ffae;
color:black;
border:none;
border-radius:8px;
margin-top:10px">
Get Started
</button>
</div>
`

/* FEATURES */

let features = `
<div style="padding:40px">

<h2>Features</h2>

<div style="display:flex;gap:20px;flex-wrap:wrap">

<div style="background:#f4f4f4;padding:20px;flex:1">
AI Builder
</div>

<div style="background:#f4f4f4;padding:20px;flex:1">
Hosting
</div>

<div style="background:#f4f4f4;padding:20px;flex:1">
Domains
</div>

</div>

</div>
`

/* FOOTER */

let footer = `
<div style="background:#02110d;color:white;padding:20px;text-align:center">
${brand} powered by Tarvex  
<br>
tarvexnetworks@gmail.com
</div>
`

/* PAGES */

siteData.home = `
${nav}
${hero}
${features}
${footer}
`

siteData.about = `
${nav}
<div style="padding:40px">
<h1>About ${brand}</h1>
<p>This website was generated by Tarvex AI</p>
</div>
${footer}
`

siteData.services = `
${nav}
<div style="padding:40px">
<h1>Services</h1>
<ul>
<li>Website Builder</li>
<li>Hosting</li>
<li>Domains</li>
<li>AI Tools</li>
</ul>
</div>
${footer}
`

siteData.contact = `
${nav}
<div style="padding:40px">
<h1>Contact</h1>
<p>Email: tarvexnetworks@gmail.com</p>
</div>
${footer}
`

/* SHOW PREVIEW */

document.getElementById("result").innerHTML = `

<h3>Website Preview</h3>

<div id="preview" style="background:white;color:black;border-radius:12px">
${siteData.home}
</div>

<button onclick="deploy()" style="
margin-top:10px;
padding:14px;
background:#00ffae;
border:none;
border-radius:10px;
width:100%;
">
Deploy Website
</button>

`

}

/* NAVIGATION */

function loadPage(page){
document.getElementById("preview").innerHTML = siteData[page]
}

/* DEPLOY */

function deploy(){

localStorage.setItem("tarvex_site", JSON.stringify(siteData))

window.location.href="deploy.html"

  }
