const TARVEX_EMAIL = "tarvexnetworks@gmail.com";

let siteData = {}

function generate(){

let text = document.getElementById("prompt").value

if(text==""){
alert("Describe website first")
return
}

/* NAVBAR */
let nav = `
<div style="background:#0b2a5b;color:white;padding:20px">
<h2>${text}</h2>
<a href="#" onclick="loadPage('index')" style="color:white;margin-right:15px">Home</a>
<a href="#" onclick="loadPage('about')" style="color:white;margin-right:15px">About</a>
<a href="#" onclick="loadPage('services')" style="color:white;margin-right:15px">Services</a>
<a href="#" onclick="loadPage('contact')" style="color:white">Contact</a>
</div>
`

/* HOME */
siteData.index = `
${nav}
<div style="padding:20px">
<h1>Welcome</h1>
<p>This website was generated by Tarvex AI</p>
</div>
`

/* ABOUT */
siteData.about = `
${nav}
<div style="padding:20px">
<h1>About</h1>
<p>This is your business description</p>
</div>
`

/* SERVICES */
siteData.services = `
${nav}
<div style="padding:20px">
<h1>Services</h1>
<ul>
<li>Website Development</li>
<li>Hosting</li>
<li>Domains</li>
</ul>
</div>
`

/* CONTACT */
siteData.contact = `
${nav}
<div style="padding:20px">
<h1>Contact</h1>
<p>Email: ${TARVEX_EMAIL}</p>
</div>
`

document.getElementById("result").style.display="block"

document.getElementById("result").innerHTML = `

<h3>Website Preview</h3>

<div id="preview" style="background:white;color:black;border-radius:10px;overflow:hidden">
${siteData.index}
</div>

<button onclick="deploy()">Deploy Website</button>

`

}

/* NAVIGATION */
function loadPage(page){
document.getElementById("preview").innerHTML = siteData[page]
}

function deploy(){

localStorage.setItem("tarvex_site", JSON.stringify(siteData))

window.location.href="deploy.html"

  }
